- name: "create user {{ client.user }}"
  user:
    name: "{{ client.user }}"
    password: "{{ client.password }}"
    group:  "{{ client.group }}"
    groups:
      - spark
  become: true
  
- name: add local public key
  authorized_key:
    user: "{{ client.user }}"
    state: present
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
  become: true
  
- name: upload site files
  copy:
    src: "{{ global.localhost.sitedir }}"
    dest: /home/{{ client.user }}
    owner: "{{ client.user }}"
    group: "{{ client.group }}"
    mode: 0744
  become: true
  
- name: update bashrc
  template:
    src: bashrc.j2
    dest: "/home/{{ client.user }}/.bashrc"
    owner: "{{ client.user }}"
    group: "{{ client.group }}"
  become: true

- name: upload client files
  copy:
    src: "{{ global.localhost.clientdir }}"
    dest: /home/{{ client.user }}
    owner: "{{ client.user }}"
    group: "{{ client.group }}"
    mode: 0744
  become: true

- name: allow PasswordAuthentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication '
    line: 'PasswordAuthentication yes'
  notify:
    - restart sshd
  become: true

