- name: "create user {{ username }}"
  user:
    name: "{{ username }}"
    # python -c 'import crypt; print crypt.crypt("password", "$1$SomeSalt$")'
    password: $1$SomeSalt$/jbIwfYCu0MxPBND2EtRH.
    groups: users,spark

- name: add local public key
  authorized_key:
    user: "{{ username }}"
    state: present
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
    
- name: set site variables
  set_fact:
    site:
      zookeeper: '{{ servers.zookeeper | join(":{0},".format( port.zookeeper )) }}:{{ port.zookeeper }}'
      elasticsearch: "http://{{ servers.elasticsearch[0] }}:{{ port.elasticsearch }}"
      kafka: "{{ servers.kafka | join(':{0},'.format( port.kafka )) }}:{{ port.kafka }}"

- name: update bashrc
  template:
    src: bashrc.j2
    dest: "/home/{{ username }}/.bashrc"
    owner: "{{ username }}"

- name: allow PasswordAuthentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication '
    line: 'PasswordAuthentication yes'
  notify:
    - restart sshd

