- hosts: all
  roles:
    - network

- hosts: zookeeper
  roles:
    - jdk
    - zookeeper
  
- hosts: kafka
  roles:
    - jdk
    - kafka

- hosts: elasticsearch
  roles:
    - jdk
    - elasticsearch
  
- hosts: kibana
  roles:
    - jdk
    - kibana

- hosts: logstash
  roles:
    - jdk
    - logstash
  
- hosts: spark-master
  roles:
    - jdk
    - spark-master

- hosts: spark-worker
  roles:
    - jdk
    - spark-worker

- hosts: nifi
  roles:
    - jdk
    - nifi

- hosts: client
  roles:
    - nano
    - client

- hosts: resources
  roles:
    - resources

- hosts: admin
  roles:
    - admin
    - stunnel

- hosts: oracle
  roles:
    - oracle-db

- hosts: docker
  roles:
    - docker
    - client

- hosts: hdp
  roles:
#    - jdk
#    - kerberos
#    - postgresql
#    - ambari
    - hdp

