- hosts: zookeeper
  roles:
    - network
    - jdk
    - zookeeper
  
- hosts: kafka
  roles:
    - network
    - jdk
    - kafka

- hosts: elasticsearch
  roles:
    - network
    - jdk
    - elasticsearch
  
- hosts: kibana
  roles:
    - network
    - jdk
    - kibana

- hosts: logstash
  roles:
    - network
    - jdk
    - logstash
  
- hosts: spark-master
  roles:
    - network
    - jdk
    - spark-master

- hosts: spark-worker
  roles:
    - network
    - jdk
    - spark-worker

- hosts: nifi
  roles:
    - network
    - jdk
    - nifi

- hosts: client
  roles:
    - nano
    - client

- hosts: resources
  roles:
    - resources

- hosts: admin
  roles:
    - network
    - admin
    - stunnel

- hosts: oracle
  roles:
    - network
    - oracle-db

- hosts: docker
  roles:
    - network
    - docker
    - client

- hosts: tools
  roles:
    - network
    - rstudio
  environment:
    http_proxy: http://{{ lookup('env','PROXY_HOST') }}:{{ lookup('env','PROXY_PORT')|default('3128',true)  }}
    https_proxy: http://{{ lookup('env','PROXY_HOST') }}:{{ lookup('env','PROXY_PORT')|default('3128',true) }}

- hosts: hdp
  roles:
    - {role: 'network', tags: 'pre'}
    - {role: 'jdk', tags: 'pre'}
    - {role: 'kerberos', tags: 'pre'}
    - {role: 'postgresql', tags: 'pre'}
    - {role: 'ambari', tags: 'pre'}
    - {role: 'hdp',  tags: 'main'}
    - {role: 'client', tags: 'post'}

  environment:
    http_proxy: http://{{ lookup('env','PROXY_HOST') }}:{{ lookup('env','PROXY_PORT')|default('3128',true)  }}
    https_proxy: http://{{ lookup('env','PROXY_HOST') }}:{{ lookup('env','PROXY_PORT')|default('3128',true) }}
    no_proxy: localhost

- hosts: hdpdock
  roles:
    - {role: 'jdk', tags: 'pre'}
    - {role: 'kerberos', tags: 'pre'}
    - {role: 'postgresql', tags: 'pre'}
    - {role: 'ambari', tags: 'pre'}
    - {role: 'hdp', tags: 'main'}
