- include_tasks: "{{ playbook_dir }}/common/install.yml"
  
- name: copy master systemd start scripts
  template:
    src: "spark-master-systemd.j2"
    dest: /etc/systemd/system/spark-master.service
    owner: root
    group: root
  when: inventory_hostname in groups['spark-master'] 
  notify: 
    - restart spark-master

- name: copy worker systemd start scripts
  template:
    src: "spark-worker-systemd.j2"
    dest: /etc/systemd/system/spark-worker.service
    owner: root
    group: root
  when: inventory_hostname in groups['spark-worker'] 
  notify: 
    - restart spark-worker

- name: start spark masters
  service: name=spark-master state=started enabled=yes 
  when: inventory_hostname in groups['spark-master']

- name: start spark workers
  service: name=spark-worker state=started enabled=yes 
  when: inventory_hostname in groups['spark-worker']
