install:
  type: archive
  module: kafka
  user: kafka
  group: kafka
  version: 1.0.0
  file: kafka/1.0.0/kafka_2.11-1.0.0.tgz
  dir: kafka_2.11-1.0.0
  port: "{{ global.ports.kafka }}"
  cfg:
    - server.properties
  services:
    - kafka
  checks:
    port: yes
