install:
  type: archive
  module: kafka
  user: kafka
  group: kafka
  version: 1.0.0
  file: kafka/1.0.0/kafka_2.11-1.0.0.tgz
  port: "{{ global.ports.kafka }}"
  cfg:
    - server.properties
  services:
    - kafka
  checks:
    port: yes
  site: site-kafka.sh
  vars:
    brokers: "{{ groups['kafka'] | intersect(play_hosts) | join(':{0},'.format( global.ports.kafka )) }}:{{ global.ports.kafka }}"
    zkconn: '{{ groups["zookeeper"] | intersect(play_hosts) | join(":{0},".format( global.ports.zookeeper )) }}:{{ global.ports.zookeeper }}'



