- name: update /etc/hosts from template
  template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root

- name: disable eth0
  lineinfile:
    path: /etc/sysconfig/network-scripts/ifcfg-eth0
    regexp: '^ONBOOT='
    line: 'ONBOOT="no"'

- name: restart network
  systemd:
    name: network
    state: restarted
    
