- name: "upload {{ package }}"
  copy:
    src: "{{ local_cache }}/{{ package }}"
    dest: "{{ dest_cache }}/{{ package }}"

- name: "install {{ package }}"
  yum:
    name: "{{ dest_cache }}/{{ package }}"
    state: present
    
- name: configure Zookeeper connection
  lineinfile:
    path: /etc/kafka/server.properties
    regexp: 'zookeeper.connect='
    line: 'zookeeper.connect={{ groups["zookeeper"] | join(":{0},".format(2181)) }}:2181'

- name: configure Broker Id
  lineinfile:
    path: /etc/kafka/server.properties
    regexp: 'broker.id='
    line: 'broker.id={{ hostvars[inventory_hostname].broker_id }}'
 
- name: start kafka
  systemd:
    state: started
    name: kafka
