- import_tasks: "{{ playbook_dir }}/common/install-rpm.yml"
  
- name: configure Zookeeper connection
  lineinfile:
    path: /etc/kafka/server.properties
    regexp: 'zookeeper.connect='
    line: 'zookeeper.connect={{ site.zookeeper }}'

- name: configure Broker Id
  lineinfile:
    path: /etc/kafka/server.properties
    regexp: 'broker.id='
    line: 'broker.id={{ hostvars[inventory_hostname].broker_id }}'
 
- name: start kafka
  systemd:
    state: started
    name: kafka
