# Generic installation playbook
# - Supports installation of RPM and (Apache) archive 
# - requires the dictionary 'install' to be defined in role's default with at least the mandatory keys:
#   type (archive or rpm), module, version, user, group
# and the optional keys: bin, url, cfg (list of files), data (idem), services idem), tests 

- set_fact:
    tmpbin: /opt/{{ install.dir }}
  when: install.dir is defined
        
- set_fact:
    tmpbin: /opt/{{ install.module }}-{{ install.version }}
  when: install.dir is not defined

# using the merge option of Ansible to extend the install dictionary 
- name: declare install.paths for {{ install.module }}  
  set_fact:
    install:
      path:
        bin: "{{ tmpbin }}"
        data: /var/lib/{{ install.module }}
        cfg: /etc/{{ install.module }}
        log: /var/log/{{ install.module }}
        opt: /opt/{{ install.module }}
        tmp: /tmp

- include_tasks: "{{ playbook_dir }}/common/install-{{ install.type }}.yml"

- include_tasks: "{{ playbook_dir }}/common/install-checks.yml"
  when: install.checks is defined
