install:
  type: rpm
  module: kibana
  version: 5.6.4
  build: "-x86_64"
  port: "{{ global.ports.kibana }}"
  url: "{{ global.mirrors.elastic }}/kibana"
  cfg:
    - kibana.yml
  checks:
    port: yes
