# Create kafka topics

- name: create Kafka topics
  shell: "/opt/kafka/bin/kafka-topics.sh --zookeeper {{ install.vars.zkconn }} --create --topic {{ item }}  --partitions {{ resources.kafka.partitions }} --replication-factor {{ resources.kafka.replication }} "
  become: kafka
  with_items: "{{ resources.kafka.topics }}"
  run_once: true
  
