# Vagrant File for ELK servers elk<N>.hostonly.com with internal IP 192.168.56.5<N>
Vagrant.configure("2") do |config|
	ssh_pub_key = File.readlines("../id_rsa.pub").first.strip
	(1..1).each do |i|
		config.vm.define "elk#{i}" do |node|
			node.vm.box = "centos/7"
			node.vm.network :private_network, ip: "192.168.56.5%d" % i
			node.vm.hostname = "elk#{i}.hostonly.com"
			node.vm.provision 'shell', inline: "echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys", 
privileged: false
			node.vm.provider "virtualbox" do |v|
			  v.name = "elk#{i}"
			  v.customize ["modifyvm", :id, "--memory", "1024"]
			  v.customize ["modifyvm", :id, "--cpus", 1]
			end
		end
	end
end

