# Create kafka topics
- set_fact:
    zkconn: '{{ groups["zookeeper"] | intersect(play_hosts) | join(":{0},".format( global.ports.zookeeper )) }}:{{ global.ports.zookeeper }}'
 
- name: create Kafka topics
  shell: "/opt/kafka/bin/kafka-topics.sh --zookeeper {{ zkconn }} --create --topic {{ item }}  --partitions {{ resources.kafka.partitions }} --replication-factor {{ resources.kafka.replication }} "
  become: kafka
  with_items: "{{ resources.kafka.topics }}"
  run_once: true
  
