install:
  type: archive
  module: kafka
  user: kafka
  group: kafka
  version: 0.10.2.1
  file: kafka/0.10.2.1/kafka_2.10-0.10.2.1.tgz
  port: "{{ global.ports.kafka }}"
  cfg:
    - server.properties
  services:
    - kafka
  checks:
    port: yes
  site: site-kafka.sh
  vars:
    brokers: "{{ groups['kafka'] | intersect(play_hosts) | join(':{0},'.format( global.ports.kafka )) }}:{{ global.ports.kafka }}"
    zkconn: '{{ groups["zookeeper"] | intersect(play_hosts) | join(":{0},".format( global.ports.zookeeper )) }}:{{ global.ports.zookeeper }}'



