install:
  type: archive
  module: spark
  version: 1.6.3
  user: spark
  group: spark
  port: "{{ global.ports.spark_worker_ui }}"
  file: spark-1.6.3/spark-1.6.3-bin-hadoop2.6.tgz
  services:
    - spark-worker
  checks:
    port: true
