- name: create PostgreSQL database for Hive
  postgresql_db:
    name: hive
  become: true
  become_user: postgres

- name: create PostgreSQL hive user
  postgresql_user:
    db: hive
    name: hive
    password: evih
  become: true
  become_user: postgres

- name: add user hive to pg_hba.conf
  lineinfile:
    path: /var/lib/pgsql/data/pg_hba.conf
    regexp: "^host  all .* 0.0.0.0/0  md5"
    line: "host  all   ambari,mapred,hive 0.0.0.0/0  md5"
  become: true  
  notify: restart postgresql

- name: add Hive service to cluster {{ hdp.cluster.name }}
  uri:
    url: http://localhost:8080/api/v1/clusters/{{ hdp.cluster.name }}/services/SERVICE
    method: POST
    user: admin
    password: "{{ hdp.cluster.pass }}"
    status_code: 201
    force_basic_auth: yes
    headers:
      X-Requested-By: "ambari"

- name: add mandatory components to Hive service
  uri:
    url: http://localhost:8080/api/v1/clusters/{{ hdp.cluster.name }}/services/HIVE/components/{{ item }}
    method: POST
    user: admin
    password: "{{ hdp.cluster.pass }}"
    status_code: 201
    force_basic_auth: yes
    headers:
      X-Requested-By: "ambari"
  with_items:
    - HCAT
    - HIVE_METASTORE
    - HIVE_SERVER
