hdp:
  name: HDP-2.6.4
  version: 2.6
  subversion: 2.6.4.0-91
  url: http://public-repo-1.hortonworks.com/HDP/centos7/2.x/updates/2.6.4.0
  utils:
    version: 1.1.0.22
    url: http://public-repo-1.hortonworks.com/HDP-UTILS-1.1.0.22/repos/centos7
  preinstall: yes
  packages:
    - hdp-select
    - zookeeper-server
    - hadoop-hdfs-datanode
    - hadoop-hdfs-namenode
    - hadoop-hdfs-secondarynamenode
    - hadoop-yarn-nodemanager 
    - hadoop-yarn-resourcemanager
    - hadoop-yarn-timelineserver
    - hadoop-mapreduce
    - hadoop-mapreduce-historyserver
    - hbase
    - hive-server
    - hive-webhcat
    - ambari-infra-solr
    - ranger-admin
    - ranger-usersync
    - ranger-tagsync
  cluster:
    name: sandbox
    password: nimda
    ranger:
      password: admin123
    kerberos:
      realm: HOSTONLY.COM
      password: nimda
  # ports to check 
  ports:
    zookeeper: 2181
    hdfs: 8020
    yarn: 8088
    mapred: 19888
    hbase: 16010
    hive: 10000
    solr: 8886
    ranger: 6080

