hdp:
  name: HDP-2.6.4
  version: 2.6
  subversion: 2.6.4.0-91
  url: http://public-repo-1.hortonworks.com/HDP/centos7/2.x/updates/2.6.4.0
  utils:
    version: 1.1.0.22
    url: http://public-repo-1.hortonworks.com/HDP-UTILS-1.1.0.22/repos/centos7
  preinstall: yes
  packages:
    - hdp-select
    - zookeeper-server
    - hadoop-hdfs-datanode
    - hadoop-hdfs-namenode
    - hadoop-hdfs-secondarynamenode
    - hadoop-yarn-nodemanager 
    - hadoop-yarn-resourcemanager
    - hadoop-yarn-timelineserver
    - hadoop-mapreduce
    - hadoop-mapreduce-historyserver
    - hbase
    - hive-server
    - hive-webhcat
    - ambari-infra-solr
    - ranger-admin
    - ranger-usersync
    - ranger-tagsync
  cluster:
    name: SANDBOX
    password: nimda
    kerberos:
      realm: HOSTONLY.COM
      password: nimda
    # ports to check 
    ports:
      zookeeper: 2181
      hdfs-namenode: 50070
      yarn-resmgr: 8088
      mapred-history: 19888
      hbase-master: 16010
      hive-server: 10000
      solr: 8886
      ranger-ui: 6080

