# dependencies
centos:
  packages_depends:
    - compat-libcap1
    - gcc
    - gcc-c++
    - glibc
    - glibc.i686
    - glibc-devel
    - glibc-devel.i686
    - ksh
    - libaio.i686
    - libaio-devel
    - libaio-devel.i686
    - libstdc++.i686
    - libstdc++-devel
    - libstdc++-devel.i686
    - libXi
    - libXi.i686
    - libXtst
    - libXtst.i686
    - sysstat
    - unixODBC
    - unzip

# users/groups
oracle_system_group: oinstall
oracle_system_user: oracle
oracle_extra_groups:
  - dba
  - oper

oracle_dba_group: dba
oracle_oper_group: oper

# kernel tuning
kernel_params:
  # Shared memory and semaphore
  # look for document 226209.1 in oracle support for details
  kernel.sem: 250 32000 100 128
  kernel.shmmni: 4096
  # 1.5 GB Shared memory 500mb for linux kernel (for 2GB virtual machine)
  kernel.shmall: 393216
  # 1 GB Half of the physical memory (for 2GB virtual machine)
  kernel.shmmax: 4398046511104
  # For 1Gbps with 1ms latency 16MB buffer
  net.core.rmem_max: 16777216
  net.core.wmem_max: 16777216
  net.ipv4.tcp_rmem: 4096 87380 16777216
  net.ipv4.tcp_wmem: 4096 65536 16777216
  # Minimize swap file use
  vm.swappiness: 10
  vm.dirty_background_ratio: 5
  vm.dirty_ratio: 10
  # Max open file descriptors 512 * db processes + room for os
  fs.file-max: 409600
  # Shorten keep alive of connections
  net.ipv4.tcp_keepalive_time: 300
  net.ipv4.tcp_keepalive_intvl: 60
  net.ipv4.tcp_keepalive_probes: 10
  # maximize port range
  net.ipv4.ip_local_port_range: 9000 65500

# system tuning
sys_config:
  hugepages_nr: 578
  limits:
    - { limit: 'soft', type: nofile, value: 4096 }
    - { limit: 'hard', type: nofile, value: 65536 }
    - { limit: 'soft', type: nproc, value: 2047 }
    - { limit: 'hard', type: nproc, value: 16384 }
    - { limit: 'soft', type: stack, value: 10240 }
    - { limit: 'hard', type: stack, value: 32768 }
    - { limit: 'soft', type: memlock, value: 1887437 }
    - { limit: 'hard', type: memlock, value: 1887437 }


# oracle parameters
oracle_version: '12.1.0.2'
oracle_edition: 'EE'
# default passwd is changeme
oracle_system_user_password: '$6$P7jw3OaWKdR$tRSRPjTey.SPqhyLBxOKbm9k21MEYF6jHDUH2O03RPvISDVnkGqWNg1W6iJqZhqD3ErbdJZqUEuNnEuoAWHWO/'
oracle_base_dir: "/opt"
oracle_installation_dir: '{{ oracle_base_dir }}/installation'
oracle_archives_directory: "/tmp"
oracle_archives_files:
  - 'linuxamd64_12102_database_1of2.zip'
  - 'linuxamd64_12102_database_2of2.zip'

oracle_server_hostname: "{{ ansible_hostname }}"
oracle_db_name: 'oradb'
oracle_home_dir: "{{ oracle_base_dir }}/{{ oracle_system_user }}/product/{{ oracle_version }}/{{ oracle_db_name }}"

# Configuration variables for Oralce instance and database installation
oracle_install:
  mode: 'INSTALL_DB_SWONLY'
  db_type: 'GENERAL_PURPOSE'
  db_globalname: 'starter'
  db_sid: 'ora'
  db_listener_port: 1521
  em_express_port: 5500
  instance_name: 'orainst'
  create_cdb: 'true'
  config_as_container_db: 'true'
  pdb_name: 'pdb_01'
  total_pdbs: '1'
  pdb_prefix: 'pdb'
  sys_dba_username: 'sys'
  starter_db_common_password: 'oracle'
  management_option: 'DEFAULT'
  enable_recovery: 'true'
  storage_type: 'FILE_SYSTEM_STORAGE'
  inventory_location: "{{ oracle_base_dir }}/inventory"
  data_location: "{{ oracle_base_dir }}/oradata"
  recovery_location: "{{ oracle_base_dir }}/recovery_area"
  decline_security_updates: 'true'
  install_samples: 'false'
  memory_option: 'false'
  memory_mb: 1536
  db_charset: 'AL32UTF8'


