install:
  type: archive
  module: spark
  version: 1.6.3
  user: spark
  group: spark
  port: "{{ global.ports.spark_master_ui }}"
  file: spark-1.6.3/spark-1.6.3-bin-without-hadoop.tgz
  site: site-spark.sh
  cfg:
    - spark-env.sh
    - spark-defaults.conf.j2
    - log4j.properties
  services:
    - spark-master
  checks:
    port: yes
    
