# install details
install:
  type: archive
  module: zookeeper
  version: 3.4.10
  user: zookeeper
  group: zookeeper
  port: "{{ global.ports.zookeeper }}"
  cfg:
    - zoo.cfg
  data:
    - myid
  services:
    - zookeeper
  checks:
    port: yes
    
