[ -f /etc/bashrc ] && . /etc/bashrc

PATH=$PATH:$HOME/bin

# load environment
[ -d env.d ] && for f in env.d/*.sh; do . $f ;done
[ -d site.d ] && for f in site.d/*.sh; do . $f ;done

# custom prompt
PS1='\[\033[1;32m\]\u@\h:\[\033[1;34m\] \w \$ \[\033[0m\]'
